apiVersion: v1
kind: Service
metadata:
  name: comment-service-svc
  namespace: comment-service-dev
  labels:
    app: comment-service
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      name: http

  type: NodePort
